apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    service: coworking
  ports:
    - name: "5153"
      protocol: TCP
      port: 5153
      targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: coworking
          image: 103245859808.dkr.ecr.us-east-1.amazonaws.com/project3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: postgresql-configmap
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-postgres-db-password
                  key: DB_PASSWORD
      restartPolicy: Always